---
- name: checks common services and packages
  hosts: all
  become: true
  roles:
    - role: common

- name: checks build server
  hosts: pkg
  become: true
  roles:
    - role: build_server

- name: checks app server
  hosts: app
  become: true
  roles:
    - role: app_server

