---
- name: checks common services and packages
  hosts: all
  become: true
  roles:
    - role: common
      priv_reg_ip_addr: 192.168.10.10

- name: checks build server
  hosts: pkg
  become: true
  roles:
    - role: build_server
      priv_reg_ip_addr: 192.168.10.10

- name: checks app server
  hosts: app
  become: true
  roles:
    - role: app_server
      priv_reg_ip_addr: 192.168.10.10
