---
# handlers file for common
- name: checks services
  systemd: name={{item}} state=started
  loop: "{{common_svc_list}}"
  loop_control:
    label: "{{item}}"
  when:
    - common_svc_list is defined
    - common_svc_list

- name: restarts docker service
  systemd: name=docker state=restarted

