---
# tasks file for app_server
- name: checks the app container
  docker_container:
    name: "{{app_cnt_name}}"
    image: "{{app_cnt_img}}"
    command: "{{app_cnt_cmd}}"
    ports: "{{app_cnt_port_list}}"
    state: started
  tags:
    - run
